### PR TITLE
Auto placement

### PR DESCRIPTION
**Pull request by SamuelBeliveau**
This PR allows the ability to automatically display the popover in the opposite direction if it cannot fit in the initial placement position.

I used the "auto" keyword inside the existing placement property, because that's what bootstrap is using, but feel free to suggest other ways.

### CODE REVIEW

**Comment by pleerock** [comment]
thanks

**Comment by pleerock** [comment]
can you please also add a sample how to use this new settings?

**Comment by GuskiS** [comment]
Can this be pushed to NPM?

**Comment by SamuelBeliveau** [comment]
I will add a sample about how to use it this week.

Thanks.

**Comment by pleerock** [comment]
released in 0.0.12

**Pull request merged**
